[package]
name = "crossbeam"
version = "0.4.0"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam"
documentation = "https://docs.rs/crossbeam"
description = "Support for concurrent programming: memory management, utilities, non-blocking data structures"
keywords = ["atomic", "garbage", "non-blocking", "lock-free", "rcu"]
categories = ["concurrency", "memory-management", "data-structures"]

[features]
nightly = ["crossbeam-epoch/nightly"]

[dependencies]
crossbeam-epoch = "0.9.11"

[dev-dependencies]
rand = "0.4"
